delete from bisis_reports.lending_action;
insert into bisis_reports.lending_action(id, description) values ('zaduzeno' ,'Zaduženo');
insert into bisis_reports.lending_action(id, description) values ('razduzeno' ,'Razduženo');
insert into bisis_reports.lending_action(id, description) values ('produzeno' ,'Produženo');

delete from bisis_reports.gender;
insert into bisis_reports.gender(id, description) values ('m' ,'Muško');
insert into bisis_reports.gender(id, description) values ('f' ,'Žensko');
insert into bisis_reports.gender(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.udk;
insert into bisis_reports.udk(id, description) values ('0' ,'Grupa 0');
insert into bisis_reports.udk(id, description) values ('1' ,'Grupa 1');
insert into bisis_reports.udk(id, description) values ('2' ,'Grupa 2');
insert into bisis_reports.udk(id, description) values ('3' ,'Grupa 3');
insert into bisis_reports.udk(id, description) values ('5' ,'Grupa 5');
insert into bisis_reports.udk(id, description) values ('6' ,'Grupa 6');
insert into bisis_reports.udk(id, description) values ('7' ,'Grupa 7');
insert into bisis_reports.udk(id, description) values ('8' ,'Grupa 8');
insert into bisis_reports.udk(id, description) values ('9' ,'Grupa 9');
insert into bisis_reports.udk(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.bibliographic_level;
insert into bisis_reports.bibliographic_level(id, description) values ('a' ,'Analitički nivo (članak)');
insert into bisis_reports.bibliographic_level(id, description) values ('c' ,'Književna zbirka -- numerisana');
insert into bisis_reports.bibliographic_level(id, description) values ('d' ,'Izvedeni radovi');
insert into bisis_reports.bibliographic_level(id, description) values ('e' ,'Književna zbirka - nenumerisana');
insert into bisis_reports.bibliographic_level(id, description) values ('m' ,'Monografska publikacija');
insert into bisis_reports.bibliographic_level(id, description) values ('s' ,'Periodična publikacija');
insert into bisis_reports.bibliographic_level(id, description) values ('r' ,'Razglednice');
insert into bisis_reports.bibliographic_level(id, description) values ('z' ,'Zbirni zapis');
update bisis_reports.bibliographic_level set description = concat(id, ' - ', description);
insert into bisis_reports.bibliographic_level(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.record_type;
insert into bisis_reports.record_type(id, description) values ('a' ,'Tekstualna građa, štampana');
insert into bisis_reports.record_type(id, description) values ('b' ,'Tekstualna građa, rukopis');
insert into bisis_reports.record_type(id, description) values ('c' ,'Note, štampane');
insert into bisis_reports.record_type(id, description) values ('d' ,'Note, rukopis');
insert into bisis_reports.record_type(id, description) values ('e' ,'Kartografska građa, štampana');
insert into bisis_reports.record_type(id, description) values ('f' ,'Kartografska građa, rukopis');
insert into bisis_reports.record_type(id, description) values ('g' ,'Audiovizuelna građa');
insert into bisis_reports.record_type(id, description) values ('i' ,'Zvučni zapisi, snimak nemuzičkih interpretacija');
insert into bisis_reports.record_type(id, description) values ('j' ,'Zvučni zapisi, snimci muzičkih interpretacija');
insert into bisis_reports.record_type(id, description) values ('k' ,'Dvodimenzionalne grafike (slike, skice)');
insert into bisis_reports.record_type(id, description) values ('l' ,'Komjuterski mediji');
insert into bisis_reports.record_type(id, description) values ('m' ,'Multimediji');
insert into bisis_reports.record_type(id, description) values ('r' ,'Trodimenzionalne umentnine i realije');
update bisis_reports.record_type set description = concat(id, ' - ', description);
insert into bisis_reports.record_type(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.serial_type;
insert into bisis_reports.serial_type(id, description) values ('a' ,'časopis');
insert into bisis_reports.serial_type(id, description) values ('b' ,'izdavačka celina');
insert into bisis_reports.serial_type(id, description) values ('c' ,'novine');
insert into bisis_reports.serial_type(id, description) values ('y' ,'magazin');
insert into bisis_reports.serial_type(id, description) values ('z' ,'ostalo');
update bisis_reports.serial_type set description = concat(id, ' - ', description);
insert into bisis_reports.serial_type(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.target;
insert into bisis_reports.target(id, description) values ('a' ,'dečja, opšta');
insert into bisis_reports.target(id, description) values ('b' ,'predškolska, 0-5 godina');
insert into bisis_reports.target(id, description) values ('c' ,'školska, 5-10 godina');
insert into bisis_reports.target(id, description) values ('d' ,'dečja, 9-14 godina');
insert into bisis_reports.target(id, description) values ('e' ,'omladinska, 14-20 godina');
insert into bisis_reports.target(id, description) values ('k' ,'za odrasle, ozbiljna');
insert into bisis_reports.target(id, description) values ('m' ,'za odrasle, opšta');
insert into bisis_reports.target(id, description) values ('u' ,'nepoznato');
update bisis_reports.target set description = concat(id, ' - ', description);
insert into bisis_reports.target(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.content_type;
insert into bisis_reports.content_type(id, description) values ('a', 'bibliografije');
insert into bisis_reports.content_type(id, description) values ('b', 'katalozi');
insert into bisis_reports.content_type(id, description) values ('c', 'kazala, indeksi');
insert into bisis_reports.content_type(id, description) values ('d', 'apstrakt');
insert into bisis_reports.content_type(id, description) values ('e', 'rečnici');
insert into bisis_reports.content_type(id, description) values ('f', 'enciklopedije');
insert into bisis_reports.content_type(id, description) values ('g', 'adresari');
insert into bisis_reports.content_type(id, description) values ('h', 'letopisi');
insert into bisis_reports.content_type(id, description) values ('i', 'statistički pregledi');
insert into bisis_reports.content_type(id, description) values ('j', 'udžbenici');
insert into bisis_reports.content_type(id, description) values ('k', 'patenti');
insert into bisis_reports.content_type(id, description) values ('l', 'standardi');
insert into bisis_reports.content_type(id, description) values ('m', 'disertacije, teze');
insert into bisis_reports.content_type(id, description) values ('m1', 'master rad');
insert into bisis_reports.content_type(id, description) values ('m2', 'magistarski radovi');
insert into bisis_reports.content_type(id, description) values ('m3', 'specijalistički radovi');
insert into bisis_reports.content_type(id, description) values ('m4', 'habilitacijski radovi');
insert into bisis_reports.content_type(id, description) values ('m5', 'diplomski radovi');
insert into bisis_reports.content_type(id, description) values ('m6', 'bečelor radovi');
insert into bisis_reports.content_type(id, description) values ('m7', 'diplomski/završni radovi prvog stepena');
insert into bisis_reports.content_type(id, description) values ('m8', 'bečelor radovi strukovnih studija');
insert into bisis_reports.content_type(id, description) values ('m9', 'specijalistički radovi strukovnih studija');
insert into bisis_reports.content_type(id, description) values ('n', 'zakoni');
insert into bisis_reports.content_type(id, description) values ('o', 'numeričke tabele');
insert into bisis_reports.content_type(id, description) values ('p', 'tehnički izveštaj');
insert into bisis_reports.content_type(id, description) values ('q', 'ispitna građa');
insert into bisis_reports.content_type(id, description) values ('r', 'istraživački radovi, bazična istraživanja');
insert into bisis_reports.content_type(id, description) values ('r1', 'prikazi');
insert into bisis_reports.content_type(id, description) values ('r2', 'naučno delo');
insert into bisis_reports.content_type(id, description) values ('r3', 'prethodno saopštenje');
insert into bisis_reports.content_type(id, description) values ('r4', 'stručno delo');
insert into bisis_reports.content_type(id, description) values ('r5', 'izveštaj sa konferencije');
insert into bisis_reports.content_type(id, description) values ('r6', 'delo nije kategorisano');
insert into bisis_reports.content_type(id, description) values ('s', 'ugovori');
insert into bisis_reports.content_type(id, description) values ('s01', 'spomenice');
insert into bisis_reports.content_type(id, description) values ('s02', 'programi');
insert into bisis_reports.content_type(id, description) values ('s03', 'poseban otisak');
insert into bisis_reports.content_type(id, description) values ('s04', 'slikovnice');
insert into bisis_reports.content_type(id, description) values ('s05', 'brošure');
insert into bisis_reports.content_type(id, description) values ('s06', 'monografije');
insert into bisis_reports.content_type(id, description) values ('s07', 'hronike');
insert into bisis_reports.content_type(id, description) values ('s08', 'studije');
insert into bisis_reports.content_type(id, description) values ('s09', 'istoriografija');
insert into bisis_reports.content_type(id, description) values ('s10', 'zbirke zadataka');
insert into bisis_reports.content_type(id, description) values ('t', 'istraživački radovi, razvojna istraživanja');
insert into bisis_reports.content_type(id, description) values ('u', 'pravilnici');
insert into bisis_reports.content_type(id, description) values ('v', 'priručnici');
insert into bisis_reports.content_type(id, description) values ('w', 'istraživački radovi, aplikacijska istraživanja');
insert into bisis_reports.content_type(id, description) values ('x1', 'atlasi');
insert into bisis_reports.content_type(id, description) values ('x2', 'separati');
insert into bisis_reports.content_type(id, description) values ('x3', 'arhivska građa');
insert into bisis_reports.content_type(id, description) values ('x4', 'albumi');
insert into bisis_reports.content_type(id, description) values ('x5', 'vodiči');
insert into bisis_reports.content_type(id, description) values ('x6', 'leksikoni');
insert into bisis_reports.content_type(id, description) values ('x7', 'statuti');
insert into bisis_reports.content_type(id, description) values ('x8', 'antologije');
insert into bisis_reports.content_type(id, description) values ('z', 'zbornici');
insert into bisis_reports.content_type(id, description) values ('z1', 'stripovi');
insert into bisis_reports.content_type(id, description) values ('z2', 'ostalo');
update bisis_reports.content_type set description = concat(id, ' - ', description);
insert into bisis_reports.content_type(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.country;
insert into bisis_reports.country(id, description) values ('KS' ,'Kraljevina Srbija');
insert into bisis_reports.country(id, description) values ('KSHS' ,'Kraljevina Srba, Hrvata i Slovenaca');
insert into bisis_reports.country(id, description) values ('abw' ,'Aruba');
insert into bisis_reports.country(id, description) values ('afg' ,'Afganistan');
insert into bisis_reports.country(id, description) values ('ago' ,'Angola');
insert into bisis_reports.country(id, description) values ('aia' ,'Anguilla');
insert into bisis_reports.country(id, description) values ('alb' ,'Albanija');
insert into bisis_reports.country(id, description) values ('and' ,'Andora');
insert into bisis_reports.country(id, description) values ('ant' ,'Holandski Antili');
insert into bisis_reports.country(id, description) values ('are' ,'Ujedinjeni Arapski Emirati');
insert into bisis_reports.country(id, description) values ('arg' ,'Argentina');
insert into bisis_reports.country(id, description) values ('asm' ,'Američka samoa');
insert into bisis_reports.country(id, description) values ('ata' ,'Antarktik (teritorija južno od 60-tog stepena JGŠ)');
insert into bisis_reports.country(id, description) values ('atf' ,'Južne francuske teritorije');
insert into bisis_reports.country(id, description) values ('atg' ,'Antigva i Barbuda');
insert into bisis_reports.country(id, description) values ('atn' ,'Dronning Moud Land');
insert into bisis_reports.country(id, description) values ('aus' ,'Australija');
insert into bisis_reports.country(id, description) values ('aut' ,'Austrija');
insert into bisis_reports.country(id, description) values ('aze' ,'Azerbejdžan');
insert into bisis_reports.country(id, description) values ('bdi' ,'Burundi');
insert into bisis_reports.country(id, description) values ('bel' ,'Belgija');
insert into bisis_reports.country(id, description) values ('ben' ,'Benin');
insert into bisis_reports.country(id, description) values ('bfa' ,'Burkina Faso');
insert into bisis_reports.country(id, description) values ('bgd' ,'Bangladeš');
insert into bisis_reports.country(id, description) values ('bgr' ,'Bugarska');
insert into bisis_reports.country(id, description) values ('bhr' ,'Bahrein');
insert into bisis_reports.country(id, description) values ('bhs' ,'Bahami');
insert into bisis_reports.country(id, description) values ('bih' ,'Bosna i Hercegovina');
insert into bisis_reports.country(id, description) values ('blr' ,'Belorusija');
insert into bisis_reports.country(id, description) values ('blz' ,'Belize');
insert into bisis_reports.country(id, description) values ('bmu' ,'Bermuda');
insert into bisis_reports.country(id, description) values ('bol' ,'Bolivija');
insert into bisis_reports.country(id, description) values ('bra' ,'Brazil');
insert into bisis_reports.country(id, description) values ('brb' ,'Barbados');
insert into bisis_reports.country(id, description) values ('brn' ,'Brunej');
insert into bisis_reports.country(id, description) values ('bth' ,'Butan');
insert into bisis_reports.country(id, description) values ('bur' ,'Burma');
insert into bisis_reports.country(id, description) values ('bvt' ,'Bouvet Island (Bouvetoya)');
insert into bisis_reports.country(id, description) values ('bwa' ,'Bocvana');
insert into bisis_reports.country(id, description) values ('bys' ,'Bjelorusija SSR');
insert into bisis_reports.country(id, description) values ('caf' ,'Centralnoafrička Republika');
insert into bisis_reports.country(id, description) values ('can' ,'Kanada');
insert into bisis_reports.country(id, description) values ('cck' ,'Cocos (Keeling) Islands');
insert into bisis_reports.country(id, description) values ('che' ,'Švajcarska');
insert into bisis_reports.country(id, description) values ('chl' ,'Čile');
insert into bisis_reports.country(id, description) values ('chn' ,'Kina');
insert into bisis_reports.country(id, description) values ('civ' ,'Obala Slonovače');
insert into bisis_reports.country(id, description) values ('cmr' ,'Kamerun');
insert into bisis_reports.country(id, description) values ('cod' ,'Demokratska Republika Kongo');
insert into bisis_reports.country(id, description) values ('cog' ,'Narodna Republika Kongo');
insert into bisis_reports.country(id, description) values ('cok' ,'Cook Islands');
insert into bisis_reports.country(id, description) values ('col' ,'Kolumbija');
insert into bisis_reports.country(id, description) values ('com' ,'Comoros');
insert into bisis_reports.country(id, description) values ('cpv' ,'Zelenortska Ostrva');
insert into bisis_reports.country(id, description) values ('cri' ,'Kostarika');
insert into bisis_reports.country(id, description) values ('csk' ,'Čehoslovačka');
insert into bisis_reports.country(id, description) values ('cte' ,'Canton and Enderbury Islands');
insert into bisis_reports.country(id, description) values ('cub' ,'Kuba');
insert into bisis_reports.country(id, description) values ('cxr' ,'Božićno Ostrvo');
insert into bisis_reports.country(id, description) values ('cym' ,'Kajmanska Ostrva');
insert into bisis_reports.country(id, description) values ('cyp' ,'Kipar');
insert into bisis_reports.country(id, description) values ('cze' ,'Češka Republika');
insert into bisis_reports.country(id, description) values ('ddr' ,'Nemačka Demokratska Republika');
insert into bisis_reports.country(id, description) values ('deu' ,'Savezna Republika Nemačka');
insert into bisis_reports.country(id, description) values ('dji' ,'Džibuti');
insert into bisis_reports.country(id, description) values ('dma' ,'Dominika');
insert into bisis_reports.country(id, description) values ('dnk' ,'Danska');
insert into bisis_reports.country(id, description) values ('dom' ,'Dominikanska Republika');
insert into bisis_reports.country(id, description) values ('dza' ,'Alžir');
insert into bisis_reports.country(id, description) values ('ecu' ,'Ekvador');
insert into bisis_reports.country(id, description) values ('egy' ,'Egipat');
insert into bisis_reports.country(id, description) values ('eri' ,'Eritreja');
insert into bisis_reports.country(id, description) values ('esh' ,'Zapadna Sahara');
insert into bisis_reports.country(id, description) values ('esp' ,'Španija');
insert into bisis_reports.country(id, description) values ('est' ,'Estonija');
insert into bisis_reports.country(id, description) values ('eth' ,'Etiopija');
insert into bisis_reports.country(id, description) values ('fin' ,'Finska');
insert into bisis_reports.country(id, description) values ('fji' ,'Fiji');
insert into bisis_reports.country(id, description) values ('flk' ,'Folklandska Ostrva (Malvinas)');
insert into bisis_reports.country(id, description) values ('fra' ,'Francuska');
insert into bisis_reports.country(id, description) values ('fro' ,'Farska Ostrva');
insert into bisis_reports.country(id, description) values ('fsm' ,'Mikronezija');
insert into bisis_reports.country(id, description) values ('gab' ,'Gabon');
insert into bisis_reports.country(id, description) values ('gbr' ,'Velika Britanija');
insert into bisis_reports.country(id, description) values ('geo' ,'Gruzija');
insert into bisis_reports.country(id, description) values ('gha' ,'Gana');
insert into bisis_reports.country(id, description) values ('gib' ,'Gibraltar');
insert into bisis_reports.country(id, description) values ('gin' ,'Gvineja');
insert into bisis_reports.country(id, description) values ('glp' ,'Gvadelupe');
insert into bisis_reports.country(id, description) values ('gmb' ,'Gambia');
insert into bisis_reports.country(id, description) values ('gnb' ,'Gvineja-Bisau');
insert into bisis_reports.country(id, description) values ('gnq' ,'Ekvatorijalna Gvineja');
insert into bisis_reports.country(id, description) values ('grc' ,'Grčka');
insert into bisis_reports.country(id, description) values ('grd' ,'Grenada');
insert into bisis_reports.country(id, description) values ('grl' ,'Grenland');
insert into bisis_reports.country(id, description) values ('gtm' ,'Gvatemala');
insert into bisis_reports.country(id, description) values ('guf' ,'Francuska Gvajana');
insert into bisis_reports.country(id, description) values ('gum' ,'Guam');
insert into bisis_reports.country(id, description) values ('guy' ,'Gvajana');
insert into bisis_reports.country(id, description) values ('hkg' ,'Hong Kong');
insert into bisis_reports.country(id, description) values ('hmd' ,'Heard and MC Donald Islands');
insert into bisis_reports.country(id, description) values ('hnd' ,'Honduras');
insert into bisis_reports.country(id, description) values ('hrv' ,'Hrvatska');
insert into bisis_reports.country(id, description) values ('hti' ,'Haiti');
insert into bisis_reports.country(id, description) values ('hun' ,'Mađarska');
insert into bisis_reports.country(id, description) values ('idn' ,'Indonezija');
insert into bisis_reports.country(id, description) values ('ind' ,'Indija');
insert into bisis_reports.country(id, description) values ('iot' ,'British Indian Ocean Territory (Chagos Archipelago)');
insert into bisis_reports.country(id, description) values ('irl' ,'Irska');
insert into bisis_reports.country(id, description) values ('irn' ,'Iran');
insert into bisis_reports.country(id, description) values ('irq' ,'Irak');
insert into bisis_reports.country(id, description) values ('isl' ,'Island');
insert into bisis_reports.country(id, description) values ('isr' ,'Izrael');
insert into bisis_reports.country(id, description) values ('ita' ,'Italija');
insert into bisis_reports.country(id, description) values ('jam' ,'Jamajka');
insert into bisis_reports.country(id, description) values ('jor' ,'Jordan');
insert into bisis_reports.country(id, description) values ('jpn' ,'Japan');
insert into bisis_reports.country(id, description) values ('jtn' ,'Johnston Island');
insert into bisis_reports.country(id, description) values ('kaz' ,'Kazahstan');
insert into bisis_reports.country(id, description) values ('ken' ,'Kenija');
insert into bisis_reports.country(id, description) values ('kgz' ,'Kirgistan');
insert into bisis_reports.country(id, description) values ('khm' ,'Kampučija (Kambodža)');
insert into bisis_reports.country(id, description) values ('kna' ,'St. Kitts and Nevis');
insert into bisis_reports.country(id, description) values ('kor' ,'Koreja, Republika (JuÅ¾na)');
insert into bisis_reports.country(id, description) values ('kwt' ,'Kuvajt');
insert into bisis_reports.country(id, description) values ('lao' ,'Laos');
insert into bisis_reports.country(id, description) values ('lbn' ,'Liban');
insert into bisis_reports.country(id, description) values ('lbr' ,'Liberija');
insert into bisis_reports.country(id, description) values ('lby' ,'Libija');
insert into bisis_reports.country(id, description) values ('lca' ,'Sveta Lucija');
insert into bisis_reports.country(id, description) values ('lie' ,'Lihtenštajn');
insert into bisis_reports.country(id, description) values ('lki' ,'Šri Lanka');
insert into bisis_reports.country(id, description) values ('lso' ,'Lesoto');
insert into bisis_reports.country(id, description) values ('ltu' ,'Litvanija');
insert into bisis_reports.country(id, description) values ('lux' ,'Luksemburg');
insert into bisis_reports.country(id, description) values ('lva' ,'Letonija');
insert into bisis_reports.country(id, description) values ('mac' ,'Makao');
insert into bisis_reports.country(id, description) values ('mar' ,'Maroko');
insert into bisis_reports.country(id, description) values ('mco' ,'Monako');
insert into bisis_reports.country(id, description) values ('mda' ,'Moldavija');
insert into bisis_reports.country(id, description) values ('mdg' ,'Madagaskar');
insert into bisis_reports.country(id, description) values ('mdv' ,'Maldivi');
insert into bisis_reports.country(id, description) values ('mex' ,'Meksiko');
insert into bisis_reports.country(id, description) values ('mhl' ,'Maršalska Ostrva');
insert into bisis_reports.country(id, description) values ('mid' ,'Midway Islands');
insert into bisis_reports.country(id, description) values ('mkd' ,'Makedonija, Bivša Jugoslovenska Republika');
insert into bisis_reports.country(id, description) values ('mli' ,'Mali');
insert into bisis_reports.country(id, description) values ('mlt' ,'Malta');
insert into bisis_reports.country(id, description) values ('mmr' ,'Myanmar');
insert into bisis_reports.country(id, description) values ('mng' ,'Mongolija');
insert into bisis_reports.country(id, description) values ('mne' ,'Crna gora');
insert into bisis_reports.country(id, description) values ('mnp' ,'Nothern Mariana Islands');
insert into bisis_reports.country(id, description) values ('moz' ,'Mozambik');
insert into bisis_reports.country(id, description) values ('mrt' ,'Mauritania');
insert into bisis_reports.country(id, description) values ('msr' ,'Montserrat');
insert into bisis_reports.country(id, description) values ('mtq' ,'Martinik');
insert into bisis_reports.country(id, description) values ('mus' ,'Mauricijus');
insert into bisis_reports.country(id, description) values ('mwi' ,'Malavi');
insert into bisis_reports.country(id, description) values ('mys' ,'Malezija');
insert into bisis_reports.country(id, description) values ('myt' ,'Mayotte');
insert into bisis_reports.country(id, description) values ('nam' ,'Nambija');
insert into bisis_reports.country(id, description) values ('ncl' ,'Nova Kaledonija');
insert into bisis_reports.country(id, description) values ('ner' ,'Niger');
insert into bisis_reports.country(id, description) values ('nfk' ,'Norfolk Island');
insert into bisis_reports.country(id, description) values ('nga' ,'Nigerija');
insert into bisis_reports.country(id, description) values ('nic' ,'Nikaragva');
insert into bisis_reports.country(id, description) values ('niu' ,'Niue');
insert into bisis_reports.country(id, description) values ('nld' ,'Holandija');
insert into bisis_reports.country(id, description) values ('nor' ,'Norveška');
insert into bisis_reports.country(id, description) values ('npl' ,'Nepal');
insert into bisis_reports.country(id, description) values ('nru' ,'Nauru');
insert into bisis_reports.country(id, description) values ('ntz' ,'Neutral Zone');
insert into bisis_reports.country(id, description) values ('nzl' ,'Novi Zeland');
insert into bisis_reports.country(id, description) values ('omn' ,'Oman');
insert into bisis_reports.country(id, description) values ('pak' ,'Pakistan');
insert into bisis_reports.country(id, description) values ('pan' ,'Panama');
insert into bisis_reports.country(id, description) values ('pci' ,'Pacific Islands (trust territory)');
insert into bisis_reports.country(id, description) values ('pcn' ,'Pitcairn Island');
insert into bisis_reports.country(id, description) values ('per' ,'Peru');
insert into bisis_reports.country(id, description) values ('phl' ,'Filipini');
insert into bisis_reports.country(id, description) values ('plw' ,'Palau');
insert into bisis_reports.country(id, description) values ('png' ,'Papua New Guinea');
insert into bisis_reports.country(id, description) values ('pol' ,'Poljska');
insert into bisis_reports.country(id, description) values ('pri' ,'Portoriko');
insert into bisis_reports.country(id, description) values ('prk' ,'Koreja, Demokratska Narodna Republika');
insert into bisis_reports.country(id, description) values ('prt' ,'Portugal');
insert into bisis_reports.country(id, description) values ('pry' ,'Paragvaj');
insert into bisis_reports.country(id, description) values ('pus' ,'United States Miscellaneous Pacific Islands');
insert into bisis_reports.country(id, description) values ('pyf' ,'Francuska Polinezija');
insert into bisis_reports.country(id, description) values ('qat' ,'Katar');
insert into bisis_reports.country(id, description) values ('reu' ,'Reunion');
insert into bisis_reports.country(id, description) values ('rom' ,'Rumunija');
insert into bisis_reports.country(id, description) values ('rus' ,'Rusija');
insert into bisis_reports.country(id, description) values ('rwa' ,'Ruanda');
insert into bisis_reports.country(id, description) values ('sau' ,'Saudijska Arabija');
insert into bisis_reports.country(id, description) values ('scg' ,'Srbija i Crna Gora');
insert into bisis_reports.country(id, description) values ('sdn' ,'Sudan');
insert into bisis_reports.country(id, description) values ('sen' ,'Senegal');
insert into bisis_reports.country(id, description) values ('sgp' ,'Singapur');
insert into bisis_reports.country(id, description) values ('sgs' ,'South Georgia and the South Sandwich Islands');
insert into bisis_reports.country(id, description) values ('shn' ,'St. Helena');
insert into bisis_reports.country(id, description) values ('sjm' ,'Svalbard and Jan Mayen Islands');
insert into bisis_reports.country(id, description) values ('slb' ,'Solomonska Ostrva');
insert into bisis_reports.country(id, description) values ('sle' ,'Sijera Leone');
insert into bisis_reports.country(id, description) values ('slv' ,'El Salvador');
insert into bisis_reports.country(id, description) values ('smr' ,'San Marino');
insert into bisis_reports.country(id, description) values ('som' ,'Somalia');
insert into bisis_reports.country(id, description) values ('spm' ,'St. Pierre and Miquelon');
insert into bisis_reports.country(id, description) values ('srb' ,'Srbija');
insert into bisis_reports.country(id, description) values ('stp' ,'Sao Tome i Principe');
insert into bisis_reports.country(id, description) values ('sun' ,'SSSR');
insert into bisis_reports.country(id, description) values ('sur' ,'Suriname');
insert into bisis_reports.country(id, description) values ('svk' ,'Slovačka');
insert into bisis_reports.country(id, description) values ('svn' ,'Slovenija');
insert into bisis_reports.country(id, description) values ('swe' ,'Švedska');
insert into bisis_reports.country(id, description) values ('swz' ,'Svazilend');
insert into bisis_reports.country(id, description) values ('syc' ,'Sejšeli');
insert into bisis_reports.country(id, description) values ('syr' ,'Sirija');
insert into bisis_reports.country(id, description) values ('tca' ,'Turks and Caicos Islands');
insert into bisis_reports.country(id, description) values ('tcd' ,'Čad');
insert into bisis_reports.country(id, description) values ('tgo' ,'Togo');
insert into bisis_reports.country(id, description) values ('tha' ,'Tajland');
insert into bisis_reports.country(id, description) values ('tjk' ,'Tadžikistan');
insert into bisis_reports.country(id, description) values ('tkl' ,'Tokelau');
insert into bisis_reports.country(id, description) values ('tkm' ,'Turkmenistan');
insert into bisis_reports.country(id, description) values ('tls' ,'Timor-Leste');
insert into bisis_reports.country(id, description) values ('tmp' ,'Istočni Timor');
insert into bisis_reports.country(id, description) values ('ton' ,'Tonga');
insert into bisis_reports.country(id, description) values ('tto' ,'Trinidad and Tobago');
insert into bisis_reports.country(id, description) values ('tun' ,'Tunis');
insert into bisis_reports.country(id, description) values ('tur' ,'Turska');
insert into bisis_reports.country(id, description) values ('tuv' ,'Tivalu');
insert into bisis_reports.country(id, description) values ('twn' ,'Tajvan');
insert into bisis_reports.country(id, description) values ('tza' ,'Tanzanija');
insert into bisis_reports.country(id, description) values ('uga' ,'Uganda');
insert into bisis_reports.country(id, description) values ('ukr' ,'Ukrajina');
insert into bisis_reports.country(id, description) values ('umi' ,'United States Minor Outlying Islands');
insert into bisis_reports.country(id, description) values ('ury' ,'Urugvaj');
insert into bisis_reports.country(id, description) values ('usa' ,'Sjedinjene Američke Države');
insert into bisis_reports.country(id, description) values ('uzb' ,'Uzbekistan');
insert into bisis_reports.country(id, description) values ('vat' ,'Vatikan');
insert into bisis_reports.country(id, description) values ('vct' ,'Saint Vincet and the Grenadines');
insert into bisis_reports.country(id, description) values ('ven' ,'Venecuela');
insert into bisis_reports.country(id, description) values ('vgb' ,'British Virgin Islands');
insert into bisis_reports.country(id, description) values ('vir' ,'United States Virgin Islands');
insert into bisis_reports.country(id, description) values ('vnm' ,'Vijetnam');
insert into bisis_reports.country(id, description) values ('vut' ,'Vanuatu');
insert into bisis_reports.country(id, description) values ('wak' ,'Wake Island');
insert into bisis_reports.country(id, description) values ('wlf' ,'Wallis and Futuna Islands');
insert into bisis_reports.country(id, description) values ('wsm' ,'Samoa');
insert into bisis_reports.country(id, description) values ('yem' ,'Jemen');
insert into bisis_reports.country(id, description) values ('ymd' ,'Jemen, Demokratska Republika');
insert into bisis_reports.country(id, description) values ('yug' ,'Jugoslavija');
insert into bisis_reports.country(id, description) values ('zaf' ,'South Africa');
insert into bisis_reports.country(id, description) values ('zar' ,'Zair');
insert into bisis_reports.country(id, description) values ('zmb' ,'Zambija');
insert into bisis_reports.country(id, description) values ('zwe' ,'Zimbabve');
update bisis_reports.country set description = concat(id, ' - ', description);
insert into bisis_reports.country(id, description) values ('nemavrednost' ,'Нема вредност');

delete from bisis_reports.language;
insert into bisis_reports.language(id, description) values ('aar' ,'Afar');
insert into bisis_reports.language(id, description) values ('abk' ,'Abhaski');
insert into bisis_reports.language(id, description) values ('ace' ,'Akineze');
insert into bisis_reports.language(id, description) values ('ach' ,'Ačoli');
insert into bisis_reports.language(id, description) values ('ada' ,'Adangme');
insert into bisis_reports.language(id, description) values ('ady' ,'Adyghe');
insert into bisis_reports.language(id, description) values ('afa' ,'Afroazijski (ostali)');
insert into bisis_reports.language(id, description) values ('afh' ,'Afrihili');
insert into bisis_reports.language(id, description) values ('afr' ,'Afrikaans');
insert into bisis_reports.language(id, description) values ('ain' ,'Ainu');
insert into bisis_reports.language(id, description) values ('ajm' ,'Aljamia');
insert into bisis_reports.language(id, description) values ('aka' ,'Akan');
insert into bisis_reports.language(id, description) values ('akk' ,'Akadski');
insert into bisis_reports.language(id, description) values ('alb' ,'Albanski');
insert into bisis_reports.language(id, description) values ('ale' ,'Aleutski');
insert into bisis_reports.language(id, description) values ('alg' ,'Algonkinski jezici');
insert into bisis_reports.language(id, description) values ('alt' ,'Altai');
insert into bisis_reports.language(id, description) values ('amh' ,'Amharski');
insert into bisis_reports.language(id, description) values ('ang' ,'Anglosaksonski (450-1100)');
insert into bisis_reports.language(id, description) values ('anp' ,'Angika');
insert into bisis_reports.language(id, description) values ('apa' ,'Apaški');
insert into bisis_reports.language(id, description) values ('ara' ,'Arapski');
insert into bisis_reports.language(id, description) values ('arc' ,'Aramejski');
insert into bisis_reports.language(id, description) values ('arg' ,'Aragonski');
insert into bisis_reports.language(id, description) values ('arm' ,'Jermenski');
insert into bisis_reports.language(id, description) values ('arn' ,'Araukanski');
insert into bisis_reports.language(id, description) values ('arp' ,'Arapaho');
insert into bisis_reports.language(id, description) values ('art' ,'veštački (drugi)');
insert into bisis_reports.language(id, description) values ('arw' ,'Aravak');
insert into bisis_reports.language(id, description) values ('asm' ,'Asamski');
insert into bisis_reports.language(id, description) values ('ast' ,'Asturian; Bable');
insert into bisis_reports.language(id, description) values ('ath' ,'Athapaskanski jezici');
insert into bisis_reports.language(id, description) values ('aus' ,'australijski jezici');
insert into bisis_reports.language(id, description) values ('ava' ,'Avarski');
insert into bisis_reports.language(id, description) values ('ave' ,'Avestički');
insert into bisis_reports.language(id, description) values ('awa' ,'Avadhi');
insert into bisis_reports.language(id, description) values ('aym' ,'Ajmara');
insert into bisis_reports.language(id, description) values ('aze' ,'Azerbejdžanski');
insert into bisis_reports.language(id, description) values ('bad' ,'Banda');
insert into bisis_reports.language(id, description) values ('bai' ,'Bamileke languages');
insert into bisis_reports.language(id, description) values ('bak' ,'Baškirski');
insert into bisis_reports.language(id, description) values ('bal' ,'Baluči');
insert into bisis_reports.language(id, description) values ('bam' ,'Bambara');
insert into bisis_reports.language(id, description) values ('ban' ,'Bali');
insert into bisis_reports.language(id, description) values ('baq' ,'Baskijski');
insert into bisis_reports.language(id, description) values ('bas' ,'Basa');
insert into bisis_reports.language(id, description) values ('bat' ,'Baltički (ostali)');
insert into bisis_reports.language(id, description) values ('bej' ,'Bedža');
insert into bisis_reports.language(id, description) values ('bel' ,'Beloruski');
insert into bisis_reports.language(id, description) values ('bem' ,'Bemba');
insert into bisis_reports.language(id, description) values ('ben' ,'Bengalski');
insert into bisis_reports.language(id, description) values ('ber' ,'Berberski jezici');
insert into bisis_reports.language(id, description) values ('bho' ,'Bhodžpuri');
insert into bisis_reports.language(id, description) values ('bih' ,'Bihari');
insert into bisis_reports.language(id, description) values ('bik' ,'Bikol');
insert into bisis_reports.language(id, description) values ('bin' ,'Bini');
insert into bisis_reports.language(id, description) values ('bis' ,'Bislama');
insert into bisis_reports.language(id, description) values ('bla' ,'Siksika / Blackfoot');
insert into bisis_reports.language(id, description) values ('bnt' ,'Bantu (ostali)');
insert into bisis_reports.language(id, description) values ('bos' ,'Bosanski (Bošnjački)');
insert into bisis_reports.language(id, description) values ('bra' ,'Bradž');
insert into bisis_reports.language(id, description) values ('bre' ,'Bretonski');
insert into bisis_reports.language(id, description) values ('btk' ,'Batak (Indonezija)');
insert into bisis_reports.language(id, description) values ('bua' ,'Buriat');
insert into bisis_reports.language(id, description) values ('bug' ,'Bugi');
insert into bisis_reports.language(id, description) values ('bul' ,'Bugarski');
insert into bisis_reports.language(id, description) values ('bur' ,'Burmanski');
insert into bisis_reports.language(id, description) values ('byn' ,'Blin / Bilin');
insert into bisis_reports.language(id, description) values ('cad' ,'Kado');
insert into bisis_reports.language(id, description) values ('cai' ,'Centralnoamerički indijanski (ostali)');
insert into bisis_reports.language(id, description) values ('cam' ,'Kmerski');
insert into bisis_reports.language(id, description) values ('car' ,'Karipski');
insert into bisis_reports.language(id, description) values ('cat' ,'Katalanski');
insert into bisis_reports.language(id, description) values ('cau' ,'Kavkaski (ostali)');
insert into bisis_reports.language(id, description) values ('ceb' ,'Kebuanski');
insert into bisis_reports.language(id, description) values ('cha' ,'Chamorro');
insert into bisis_reports.language(id, description) values ('chb' ,'Čibča');
insert into bisis_reports.language(id, description) values ('che' ,'Čečenski');
insert into bisis_reports.language(id, description) values ('chg' ,'Čagatai');
insert into bisis_reports.language(id, description) values ('chi' ,'Kineski');
insert into bisis_reports.language(id, description) values ('chk' ,'Chuukese');
insert into bisis_reports.language(id, description) values ('chm' ,'Mari');
insert into bisis_reports.language(id, description) values ('chn' ,'Činuk žargon');
insert into bisis_reports.language(id, description) values ('cho' ,'Chocktaw');
insert into bisis_reports.language(id, description) values ('chp' ,'Chipewyan');
insert into bisis_reports.language(id, description) values ('chr' ,'Čeroki');
insert into bisis_reports.language(id, description) values ('chu' ,'Crkvenoslovenski');
insert into bisis_reports.language(id, description) values ('chv' ,'Čuvaški');
insert into bisis_reports.language(id, description) values ('chy' ,'Čejenski');
insert into bisis_reports.language(id, description) values ('cmc' ,'Chamic languages');
insert into bisis_reports.language(id, description) values ('cop' ,'Koptski');
insert into bisis_reports.language(id, description) values ('cor' ,'Cornish');
insert into bisis_reports.language(id, description) values ('cos' ,'Korzikanski');
insert into bisis_reports.language(id, description) values ('cpe' ,'Kreolski i pidgin, na osnovi engleskog (ostali)');
insert into bisis_reports.language(id, description) values ('cpf' ,'Kreolski i pidgin, na osnovi francuskog (ostali)');
insert into bisis_reports.language(id, description) values ('cpp' ,'Kreolski i pidgin, na osnovi portugalskog (ostali)');
insert into bisis_reports.language(id, description) values ('cre' ,'Kri');
insert into bisis_reports.language(id, description) values ('crh' ,'Krimski tatarski / krimski turski');
insert into bisis_reports.language(id, description) values ('crp' ,'Kreolski i pidgin (ostali)');
insert into bisis_reports.language(id, description) values ('csb' ,'Kashubian');
insert into bisis_reports.language(id, description) values ('cus' ,'Kušitski (ostali)');
insert into bisis_reports.language(id, description) values ('cze' ,'Češki');
insert into bisis_reports.language(id, description) values ('dak' ,'Dakota');
insert into bisis_reports.language(id, description) values ('dan' ,'Danski');
insert into bisis_reports.language(id, description) values ('del' ,'Delaware');
insert into bisis_reports.language(id, description) values ('den' ,'Slave (Athapascan)');
insert into bisis_reports.language(id, description) values ('dgr' ,'Dogrib');
insert into bisis_reports.language(id, description) values ('din' ,'Dinka');
insert into bisis_reports.language(id, description) values ('div' ,'Divehi');
insert into bisis_reports.language(id, description) values ('doi' ,'Dogri');
insert into bisis_reports.language(id, description) values ('dra' ,'Dravidski (ostali)');
insert into bisis_reports.language(id, description) values ('dsb' ,'Donji Lužičko-srpski - Lower Sorbian');
insert into bisis_reports.language(id, description) values ('dua' ,'Duala');
insert into bisis_reports.language(id, description) values ('dum' ,'Srednjoholandski (1050-1350)');
insert into bisis_reports.language(id, description) values ('dut' ,'Holandski, Flamanski');
insert into bisis_reports.language(id, description) values ('dyu' ,'Dyula');
insert into bisis_reports.language(id, description) values ('dzo' ,'Dzongkha');
insert into bisis_reports.language(id, description) values ('efi' ,'Efik');
insert into bisis_reports.language(id, description) values ('egy' ,'Egipatski (stari)');
insert into bisis_reports.language(id, description) values ('eka' ,'Ekajuk');
insert into bisis_reports.language(id, description) values ('elx' ,'Elamitski');
insert into bisis_reports.language(id, description) values ('eng' ,'Engleski');
insert into bisis_reports.language(id, description) values ('enm' ,'Srednjoengleski (1100-1500)');
insert into bisis_reports.language(id, description) values ('epo' ,'Esperanto');
insert into bisis_reports.language(id, description) values ('esk' ,'Eskimski');
insert into bisis_reports.language(id, description) values ('est' ,'Estonski');
insert into bisis_reports.language(id, description) values ('eth' ,'Etiopski');
insert into bisis_reports.language(id, description) values ('ewe' ,'Ewe');
insert into bisis_reports.language(id, description) values ('ewo' ,'Ewondo');
insert into bisis_reports.language(id, description) values ('fan' ,'Fang');
insert into bisis_reports.language(id, description) values ('far' ,'Faroese');
insert into bisis_reports.language(id, description) values ('fat' ,'Fanti');
insert into bisis_reports.language(id, description) values ('fij' ,'Fijian');
insert into bisis_reports.language(id, description) values ('fil' ,'Filipinski');
insert into bisis_reports.language(id, description) values ('fin' ,'Finski');
insert into bisis_reports.language(id, description) values ('fiu' ,'Ugrofinski (ostali)');
insert into bisis_reports.language(id, description) values ('fon' ,'Fon');
insert into bisis_reports.language(id, description) values ('fre' ,'Francuski');
insert into bisis_reports.language(id, description) values ('frm' ,'Srednjofrancuski (1400-1600)');
insert into bisis_reports.language(id, description) values ('fro' ,'Starofrancuski (842-1400)');
insert into bisis_reports.language(id, description) values ('fry' ,'Frizijski');
insert into bisis_reports.language(id, description) values ('frr' ,'North Frizian');
insert into bisis_reports.language(id, description) values ('frs' ,'East Frizian');
insert into bisis_reports.language(id, description) values ('ful' ,'Fulah');
insert into bisis_reports.language(id, description) values ('fur' ,'Friulian');
insert into bisis_reports.language(id, description) values ('gaa' ,'Ga');
insert into bisis_reports.language(id, description) values ('gal' ,'Galla');
insert into bisis_reports.language(id, description) values ('gay' ,'Gayo');
insert into bisis_reports.language(id, description) values ('gba' ,'Gbaya');
insert into bisis_reports.language(id, description) values ('gem' ,'Germanski (ostali)');
insert into bisis_reports.language(id, description) values ('geo' ,'Gruzijski');
insert into bisis_reports.language(id, description) values ('ger' ,'Nemački');
insert into bisis_reports.language(id, description) values ('gez' ,'Geez');
insert into bisis_reports.language(id, description) values ('gil' ,'Gilbertese');
insert into bisis_reports.language(id, description) values ('gla' ,'Gelik / Å kotski gelik');
insert into bisis_reports.language(id, description) values ('gle' ,'Irski');
insert into bisis_reports.language(id, description) values ('glg' ,'Gallegan');
insert into bisis_reports.language(id, description) values ('glv' ,'Manx');
insert into bisis_reports.language(id, description) values ('gmh' ,'Srednjovisokonemački (1050-1500)');
insert into bisis_reports.language(id, description) values ('goh' ,'Starovisokonemački (750-1050)');
insert into bisis_reports.language(id, description) values ('gon' ,'Gondski');
insert into bisis_reports.language(id, description) values ('gor' ,'Gorontalo');
insert into bisis_reports.language(id, description) values ('got' ,'Gotski');
insert into bisis_reports.language(id, description) values ('grb' ,'Grebo');
insert into bisis_reports.language(id, description) values ('grc' ,'Starogrčki (-1453)');
insert into bisis_reports.language(id, description) values ('gre' ,'Grčki (1453-)');
insert into bisis_reports.language(id, description) values ('gsw' ,'Swiss German');
insert into bisis_reports.language(id, description) values ('gua' ,'Guarani');
insert into bisis_reports.language(id, description) values ('guj' ,'Gudžarati');
insert into bisis_reports.language(id, description) values ('gwi' ,'Gwich''in');
insert into bisis_reports.language(id, description) values ('hai' ,'Haida');
insert into bisis_reports.language(id, description) values ('hat' ,'Haitian / Haitian Creole');
insert into bisis_reports.language(id, description) values ('hau' ,'Hausa');
insert into bisis_reports.language(id, description) values ('haw' ,'Havajski');
insert into bisis_reports.language(id, description) values ('heb' ,'Hebrejski');
insert into bisis_reports.language(id, description) values ('her' ,'Herero');
insert into bisis_reports.language(id, description) values ('hil' ,'Hiligaynon');
insert into bisis_reports.language(id, description) values ('him' ,'Himačali');
insert into bisis_reports.language(id, description) values ('hin' ,'Hindi');
insert into bisis_reports.language(id, description) values ('hit' ,'Hittite');
insert into bisis_reports.language(id, description) values ('hmn' ,'Hmong');
insert into bisis_reports.language(id, description) values ('hmo' ,'Hiri motu');
insert into bisis_reports.language(id, description) values ('hrv' ,'Hrvatski');
insert into bisis_reports.language(id, description) values ('hsb' ,'Gornji Lužičko-srpski (Upper Sorbian)');
insert into bisis_reports.language(id, description) values ('hun' ,'Madjarski');
insert into bisis_reports.language(id, description) values ('hup' ,'Hupa');
insert into bisis_reports.language(id, description) values ('iba' ,'Iban');
insert into bisis_reports.language(id, description) values ('ibo' ,'Igbo');
insert into bisis_reports.language(id, description) values ('ice' ,'Islandski');
insert into bisis_reports.language(id, description) values ('ido' ,'Ido');
insert into bisis_reports.language(id, description) values ('iii' ,'Sichuan Yi');
insert into bisis_reports.language(id, description) values ('ijo' ,'Ijo');
insert into bisis_reports.language(id, description) values ('iku' ,'Inuktitut');
insert into bisis_reports.language(id, description) values ('ile' ,'Interlingue');
insert into bisis_reports.language(id, description) values ('ilo' ,'Iloko');
insert into bisis_reports.language(id, description) values ('ina' ,'Interlingua (International Auxiliary Language Association)');
insert into bisis_reports.language(id, description) values ('inc' ,'Indijski (ostali)');
insert into bisis_reports.language(id, description) values ('ind' ,'Indonezijski');
insert into bisis_reports.language(id, description) values ('ine' ,'Indoevropski (ostali)');
insert into bisis_reports.language(id, description) values ('inh' ,'Ingush');
insert into bisis_reports.language(id, description) values ('ipk' ,'Inupiak');
insert into bisis_reports.language(id, description) values ('ira' ,'Iranski (ostali)');
insert into bisis_reports.language(id, description) values ('iro' ,'Irokeski jezici');
insert into bisis_reports.language(id, description) values ('ita' ,'Italijanski');
insert into bisis_reports.language(id, description) values ('jav' ,'Javanski');
insert into bisis_reports.language(id, description) values ('jbo' ,'Lojban');
insert into bisis_reports.language(id, description) values ('jpn' ,'Japanski');
insert into bisis_reports.language(id, description) values ('jpr' ,'Judeo-Persian');
insert into bisis_reports.language(id, description) values ('jrb' ,'Judeo-Arabic');
insert into bisis_reports.language(id, description) values ('kaa' ,'Kara-Kalpak');
insert into bisis_reports.language(id, description) values ('kab' ,'Kabilski');
insert into bisis_reports.language(id, description) values ('kac' ,'Kachin');
insert into bisis_reports.language(id, description) values ('kal' ,'Kalaallisut / Greenlandic');
insert into bisis_reports.language(id, description) values ('kam' ,'Kamba');
insert into bisis_reports.language(id, description) values ('kan' ,'Kannada');
insert into bisis_reports.language(id, description) values ('kar' ,'Karen');
insert into bisis_reports.language(id, description) values ('kas' ,'Kašmirski');
insert into bisis_reports.language(id, description) values ('kau' ,'Kanuri');
insert into bisis_reports.language(id, description) values ('kaw' ,'Kavi');
insert into bisis_reports.language(id, description) values ('kaz' ,'Kazahski');
insert into bisis_reports.language(id, description) values ('kbd' ,'Kabardian');
insert into bisis_reports.language(id, description) values ('kha' ,'Khasi');
insert into bisis_reports.language(id, description) values ('khi' ,'Khoisan (other)');
insert into bisis_reports.language(id, description) values ('khm' ,'Kmerski');
insert into bisis_reports.language(id, description) values ('kho' ,'Khotanese');
insert into bisis_reports.language(id, description) values ('kik' ,'Kikuyu');
insert into bisis_reports.language(id, description) values ('kin' ,'Kinyarwanda');
insert into bisis_reports.language(id, description) values ('kir' ,'Kirgiski');
insert into bisis_reports.language(id, description) values ('kmb' ,'Kimbundu');
insert into bisis_reports.language(id, description) values ('kok' ,'Konkani');
insert into bisis_reports.language(id, description) values ('kom' ,'Komi');
insert into bisis_reports.language(id, description) values ('kon' ,'Kongo');
insert into bisis_reports.language(id, description) values ('kor' ,'Korejski');
insert into bisis_reports.language(id, description) values ('kos' ,'Kosraean');
insert into bisis_reports.language(id, description) values ('kpe' ,'Kpelle');
insert into bisis_reports.language(id, description) values ('krc' ,'Karachay-Balkar');
insert into bisis_reports.language(id, description) values ('krl' ,'Karelian');
insert into bisis_reports.language(id, description) values ('kro' ,'Kru');
insert into bisis_reports.language(id, description) values ('kru' ,'Kurukh');
insert into bisis_reports.language(id, description) values ('kua' ,'Kuanyama / Kwanyama');
insert into bisis_reports.language(id, description) values ('kur' ,'Kurdski');
insert into bisis_reports.language(id, description) values ('kus' ,'Kusai');
insert into bisis_reports.language(id, description) values ('kut' ,'Kutenai');
insert into bisis_reports.language(id, description) values ('lad' ,'Ladino');
insert into bisis_reports.language(id, description) values ('lah' ,'Lahnda');
insert into bisis_reports.language(id, description) values ('lam' ,'Lamba');
insert into bisis_reports.language(id, description) values ('lan' ,'Langdok (posle 1500)');
insert into bisis_reports.language(id, description) values ('lao' ,'Lao');
insert into bisis_reports.language(id, description) values ('lap' ,'Laponski');
insert into bisis_reports.language(id, description) values ('lat' ,'Latinski');
insert into bisis_reports.language(id, description) values ('lav' ,'Letonski');
insert into bisis_reports.language(id, description) values ('lez' ,'Lezghian');
insert into bisis_reports.language(id, description) values ('lim' ,'Limburgan / Limburgish');
insert into bisis_reports.language(id, description) values ('lin' ,'Lingala');
insert into bisis_reports.language(id, description) values ('lit' ,'Litvanski');
insert into bisis_reports.language(id, description) values ('lol' ,'Mongo');
insert into bisis_reports.language(id, description) values ('loz' ,'Lozi');
insert into bisis_reports.language(id, description) values ('ltz' ,'Luxemburški');
insert into bisis_reports.language(id, description) values ('lua' ,'Luba-Lulua');
insert into bisis_reports.language(id, description) values ('lub' ,'Luba-Katanga');
insert into bisis_reports.language(id, description) values ('lug' ,'Ganda');
insert into bisis_reports.language(id, description) values ('lui' ,'Luiseno');
insert into bisis_reports.language(id, description) values ('lun' ,'Lunda');
insert into bisis_reports.language(id, description) values ('luo' ,'Luo (Kenija i Tanzanija)');
insert into bisis_reports.language(id, description) values ('lus' ,'Lushai');
insert into bisis_reports.language(id, description) values ('mac' ,'Makedonski');
insert into bisis_reports.language(id, description) values ('mad' ,'Madurski');
insert into bisis_reports.language(id, description) values ('mag' ,'Magahi');
insert into bisis_reports.language(id, description) values ('mah' ,'Maršalski');
insert into bisis_reports.language(id, description) values ('mai' ,'Maithili');
insert into bisis_reports.language(id, description) values ('mak' ,'Makasar');
insert into bisis_reports.language(id, description) values ('mal' ,'Malajalamski');
insert into bisis_reports.language(id, description) values ('man' ,'Mandingo');
insert into bisis_reports.language(id, description) values ('mao' ,'Maorski');
insert into bisis_reports.language(id, description) values ('map' ,'Austronezijski (ostali)');
insert into bisis_reports.language(id, description) values ('mar' ,'Marathi');
insert into bisis_reports.language(id, description) values ('mas' ,'Masai');
insert into bisis_reports.language(id, description) values ('max' ,'Manski');
insert into bisis_reports.language(id, description) values ('may' ,'Malajski');
insert into bisis_reports.language(id, description) values ('mdf' ,'Moksha');
insert into bisis_reports.language(id, description) values ('mdr' ,'Mandar');
insert into bisis_reports.language(id, description) values ('men' ,'Mende');
insert into bisis_reports.language(id, description) values ('mga' ,'Srednjoirski (900-1200)');
insert into bisis_reports.language(id, description) values ('mic' ,'Mikmak');
insert into bisis_reports.language(id, description) values ('min' ,'Mingangkabau');
insert into bisis_reports.language(id, description) values ('mis' ,'Ostali');
insert into bisis_reports.language(id, description) values ('mkh' ,'Mon-Khmer (ostali)');
insert into bisis_reports.language(id, description) values ('mla' ,'Malagaški');
insert into bisis_reports.language(id, description) values ('mlt' ,'Malteški');
insert into bisis_reports.language(id, description) values ('mnc' ,'Manču');
insert into bisis_reports.language(id, description) values ('mni' ,'Manipuri');
insert into bisis_reports.language(id, description) values ('mno' ,'Manobo jezici');
insert into bisis_reports.language(id, description) values ('moh' ,'Mohawk');
insert into bisis_reports.language(id, description) values ('mon' ,'Mongolski');
insert into bisis_reports.language(id, description) values ('mos' ,'Mosi');
insert into bisis_reports.language(id, description) values ('mul' ,'višejezični');
insert into bisis_reports.language(id, description) values ('mun' ,'Munda');
insert into bisis_reports.language(id, description) values ('mus' ,'Creek / Muskogee');
insert into bisis_reports.language(id, description) values ('mwl' ,'Mirandese');
insert into bisis_reports.language(id, description) values ('mwr' ,'Marvari');
insert into bisis_reports.language(id, description) values ('myn' ,'Maja jezici');
insert into bisis_reports.language(id, description) values ('myv' ,'Erzya');
insert into bisis_reports.language(id, description) values ('nah' ,'Nahuatl');
insert into bisis_reports.language(id, description) values ('nai' ,'Severnoamerički indijanski (ostali)');
insert into bisis_reports.language(id, description) values ('nap' ,'Napolitan');
insert into bisis_reports.language(id, description) values ('nau' ,'Nauru');
insert into bisis_reports.language(id, description) values ('nav' ,'Navaho');
insert into bisis_reports.language(id, description) values ('nbl' ,'Ndebele, južni');
insert into bisis_reports.language(id, description) values ('nde' ,'Ndebele, severni');
insert into bisis_reports.language(id, description) values ('ndo' ,'Ndonga');
insert into bisis_reports.language(id, description) values ('nds' ,'Niskonemački / Niskosaksonski');
insert into bisis_reports.language(id, description) values ('nep' ,'Nepalski');
insert into bisis_reports.language(id, description) values ('new' ,'Newari / Nepal Bhasa');
insert into bisis_reports.language(id, description) values ('nia' ,'Nias');
insert into bisis_reports.language(id, description) values ('nic' ,'Nigersko-kordofanski (ostali)');
insert into bisis_reports.language(id, description) values ('niu' ,'Niuean');
insert into bisis_reports.language(id, description) values ('nno' ,'Norwegian Nynorsk');
insert into bisis_reports.language(id, description) values ('nob' ,'Norwegian Bokmal');
insert into bisis_reports.language(id, description) values ('nog' ,'Nogai');
insert into bisis_reports.language(id, description) values ('non' ,'Norse, Old');
insert into bisis_reports.language(id, description) values ('nor' ,'Norveški');
insert into bisis_reports.language(id, description) values ('nso' ,'Severni Sotho / Pedi / Sepedi');
insert into bisis_reports.language(id, description) values ('nqo' ,'N Ko');
insert into bisis_reports.language(id, description) values ('nub' ,'Nubijski jezici');
insert into bisis_reports.language(id, description) values ('nwc' ,'Classical Newari / Old Newari / Classical Nepal Bhasa');
insert into bisis_reports.language(id, description) values ('nya' ,'Chichewa / Chewa / Nyanja');
insert into bisis_reports.language(id, description) values ('nym' ,'Nyamwezi');
insert into bisis_reports.language(id, description) values ('nyn' ,'Nyankole');
insert into bisis_reports.language(id, description) values ('nyo' ,'Nyoro');
insert into bisis_reports.language(id, description) values ('nzi' ,'Nzima');
insert into bisis_reports.language(id, description) values ('oci' ,'Occitan / Provansalski (posle 1500)');
insert into bisis_reports.language(id, description) values ('oji' ,'Ojibwa');
insert into bisis_reports.language(id, description) values ('ori' ,'Oriya');
insert into bisis_reports.language(id, description) values ('orm' ,'Oromo');
insert into bisis_reports.language(id, description) values ('osa' ,'Osage');
insert into bisis_reports.language(id, description) values ('oss' ,'Osetski');
insert into bisis_reports.language(id, description) values ('ota' ,'Otomanski turski (1500-1928)');
insert into bisis_reports.language(id, description) values ('oto' ,'Otomski jezici');
insert into bisis_reports.language(id, description) values ('paa' ,'Papuanski (ostali)');
insert into bisis_reports.language(id, description) values ('pag' ,'Pangasinan');
insert into bisis_reports.language(id, description) values ('pal' ,'Pahlavi');
insert into bisis_reports.language(id, description) values ('pam' ,'Pampanga');
insert into bisis_reports.language(id, description) values ('pan' ,'Panjabi / Punjabi');
insert into bisis_reports.language(id, description) values ('pap' ,'Papiamento');
insert into bisis_reports.language(id, description) values ('pau' ,'Palauan');
insert into bisis_reports.language(id, description) values ('peo' ,'Staropersijski (600pne-400ne)');
insert into bisis_reports.language(id, description) values ('per' ,'Persijski');
insert into bisis_reports.language(id, description) values ('phi' ,'Filipinski (ostali)');
insert into bisis_reports.language(id, description) values ('phn' ,'Feničanski');
insert into bisis_reports.language(id, description) values ('pli' ,'Pali');
insert into bisis_reports.language(id, description) values ('pol' ,'Poljski');
insert into bisis_reports.language(id, description) values ('pon' ,'Pohnpeian');
insert into bisis_reports.language(id, description) values ('por' ,'Portugalski');
insert into bisis_reports.language(id, description) values ('pra' ,'Prakrit languages');
insert into bisis_reports.language(id, description) values ('pro' ,'Provansalski (do 1500)');
insert into bisis_reports.language(id, description) values ('pus' ,'Pushto');
insert into bisis_reports.language(id, description) values ('que' ,'Quechua');
insert into bisis_reports.language(id, description) values ('raj' ,'Rajasthani');
insert into bisis_reports.language(id, description) values ('rap' ,'Rapanui');
insert into bisis_reports.language(id, description) values ('rar' ,'Rarotongan');
insert into bisis_reports.language(id, description) values ('roa' ,'Romanski (ostali)');
insert into bisis_reports.language(id, description) values ('roh' ,'Retoromanski');
insert into bisis_reports.language(id, description) values ('rom' ,'Romski');
insert into bisis_reports.language(id, description) values ('rsi' ,'Rusinski');
insert into bisis_reports.language(id, description) values ('rum' ,'Rumunski');
insert into bisis_reports.language(id, description) values ('run' ,'Rundi');
insert into bisis_reports.language(id, description) values ('rus' ,'Ruski');
insert into bisis_reports.language(id, description) values ('rup' ,'Aromanian');
insert into bisis_reports.language(id, description) values ('sad' ,'Sandawe');
insert into bisis_reports.language(id, description) values ('sag' ,'Sango');
insert into bisis_reports.language(id, description) values ('sah' ,'Yakut');
insert into bisis_reports.language(id, description) values ('sai' ,'Južnoamerički indijanski (ostali)');
insert into bisis_reports.language(id, description) values ('sal' ,'Sališki jezici');
insert into bisis_reports.language(id, description) values ('sam' ,'Samaritanski aramejski');
insert into bisis_reports.language(id, description) values ('san' ,'Sanskrt');
insert into bisis_reports.language(id, description) values ('sas' ,'Sasak');
insert into bisis_reports.language(id, description) values ('sat' ,'Santali');
insert into bisis_reports.language(id, description) values ('scc' ,'Srpski - ćirilica');
insert into bisis_reports.language(id, description) values ('srp' ,'Srpski');
insert into bisis_reports.language(id, description) values ('scn' ,'Sicilijanski');
insert into bisis_reports.language(id, description) values ('sco' ,'Škotski');
insert into bisis_reports.language(id, description) values ('scr' ,'Srpski - latinica');	
insert into bisis_reports.language(id, description) values ('sel' ,'Selkupski');
insert into bisis_reports.language(id, description) values ('sem' ,'Semitski (ostali)');
insert into bisis_reports.language(id, description) values ('sga' ,'Irski, stari (do 900)');
insert into bisis_reports.language(id, description) values ('sgn' ,'Znakovni jezici');
insert into bisis_reports.language(id, description) values ('shn' ,'Shan');
insert into bisis_reports.language(id, description) values ('sid' ,'Sidamo');
insert into bisis_reports.language(id, description) values ('sin' ,'Sinhala');
insert into bisis_reports.language(id, description) values ('sio' ,'Siouan languages');
insert into bisis_reports.language(id, description) values ('sit' ,'Sino-Tibetan (other)');
insert into bisis_reports.language(id, description) values ('sla' ,'Slovenski (ostali)');
insert into bisis_reports.language(id, description) values ('slo' ,'Slovački');
insert into bisis_reports.language(id, description) values ('slv' ,'Slovenački');
insert into bisis_reports.language(id, description) values ('sma' ,'Southern Sami');
insert into bisis_reports.language(id, description) values ('sme' ,'Northern Sami');
insert into bisis_reports.language(id, description) values ('smi' ,'Sami languages (other)');
insert into bisis_reports.language(id, description) values ('smj' ,'Lule Sami');
insert into bisis_reports.language(id, description) values ('smn' ,'Inari Sami');
insert into bisis_reports.language(id, description) values ('smo' ,'Samoanski');
insert into bisis_reports.language(id, description) values ('sms' ,'Skolt Sami');
insert into bisis_reports.language(id, description) values ('sna' ,'Shona');
insert into bisis_reports.language(id, description) values ('snd' ,'Sindhi');
insert into bisis_reports.language(id, description) values ('snk' ,'Soninke');
insert into bisis_reports.language(id, description) values ('sog' ,'Sogdijski');
insert into bisis_reports.language(id, description) values ('som' ,'Somalijski');
insert into bisis_reports.language(id, description) values ('son' ,'Songhai');
insert into bisis_reports.language(id, description) values ('sot' ,'Sotho, Southern');
insert into bisis_reports.language(id, description) values ('spa' ,'Španski / Kastiljanski');
insert into bisis_reports.language(id, description) values ('srd' ,'Sardinijski');
insert into bisis_reports.language(id, description) values ('srr' ,'Serer');
insert into bisis_reports.language(id, description) values ('srn' ,'Sranan');
insert into bisis_reports.language(id, description) values ('ssa' ,'Nilsko-saharski (ostali)');
insert into bisis_reports.language(id, description) values ('suk' ,'Sukuma');
insert into bisis_reports.language(id, description) values ('sun' ,'Sundski');
insert into bisis_reports.language(id, description) values ('sus' ,'Susu');
insert into bisis_reports.language(id, description) values ('sux' ,'Sumerijanski');
insert into bisis_reports.language(id, description) values ('swa' ,'Svahili');
insert into bisis_reports.language(id, description) values ('swe' ,'Švedski');
insert into bisis_reports.language(id, description) values ('swz' ,'Swazi');
insert into bisis_reports.language(id, description) values ('syr' ,'Sirijski');
insert into bisis_reports.language(id, description) values ('syc' ,'Syriac');
insert into bisis_reports.language(id, description) values ('tah' ,'Tahitski');
insert into bisis_reports.language(id, description) values ('tai' ,'Tai (ostali)');
insert into bisis_reports.language(id, description) values ('tam' ,'Tamilski');
insert into bisis_reports.language(id, description) values ('tat' ,'Tatarski');
insert into bisis_reports.language(id, description) values ('tel' ,'Telugu');
insert into bisis_reports.language(id, description) values ('tem' ,'Timne');
insert into bisis_reports.language(id, description) values ('ter' ,'Tereno');
insert into bisis_reports.language(id, description) values ('tet' ,'Tetum');
insert into bisis_reports.language(id, description) values ('tgk' ,'Tadžik');
insert into bisis_reports.language(id, description) values ('tgl' ,'Tagalog');
insert into bisis_reports.language(id, description) values ('tha' ,'Thai');
insert into bisis_reports.language(id, description) values ('tib' ,'Tibetanski');
insert into bisis_reports.language(id, description) values ('tig' ,'Tigre');
insert into bisis_reports.language(id, description) values ('tir' ,'Tigrinya');
insert into bisis_reports.language(id, description) values ('tiv' ,'Tiv');
insert into bisis_reports.language(id, description) values ('tkl' ,'Tokelau');
insert into bisis_reports.language(id, description) values ('tlh' ,'Klingon');
insert into bisis_reports.language(id, description) values ('tli' ,'Tlingit');
insert into bisis_reports.language(id, description) values ('tmh' ,'Tamashek');
insert into bisis_reports.language(id, description) values ('tog' ,'Tonga (Nyasa)');
insert into bisis_reports.language(id, description) values ('ton' ,'Tonga (Tonga Islands)');
insert into bisis_reports.language(id, description) values ('tpi' ,'Tok Pisin');
insert into bisis_reports.language(id, description) values ('tsi' ,'Cimšijen');
insert into bisis_reports.language(id, description) values ('tsn' ,'Tswana');
insert into bisis_reports.language(id, description) values ('tso' ,'Tsonga');
insert into bisis_reports.language(id, description) values ('tuk' ,'Turkmen');
insert into bisis_reports.language(id, description) values ('tum' ,'Tumbuka');
insert into bisis_reports.language(id, description) values ('tup' ,'Tupi jezici');
insert into bisis_reports.language(id, description) values ('tur' ,'Turski');
insert into bisis_reports.language(id, description) values ('tut' ,'Altajski (ostali)');
insert into bisis_reports.language(id, description) values ('tvl' ,'Tuvalu');
insert into bisis_reports.language(id, description) values ('twi' ,'Twi');
insert into bisis_reports.language(id, description) values ('tyv' ,'Tuvinian');
insert into bisis_reports.language(id, description) values ('udm' ,'Udmurt');
insert into bisis_reports.language(id, description) values ('uga' ,'Ugaritic');
insert into bisis_reports.language(id, description) values ('uig' ,'Uighur / Uyghur');
insert into bisis_reports.language(id, description) values ('ukr' ,'Ukrajinski');
insert into bisis_reports.language(id, description) values ('umb' ,'Umbundu');
insert into bisis_reports.language(id, description) values ('und' ,'neodređeni');
insert into bisis_reports.language(id, description) values ('urd' ,'Urdu');
insert into bisis_reports.language(id, description) values ('uzb' ,'Uzbečki');
insert into bisis_reports.language(id, description) values ('vai' ,'Vai');
insert into bisis_reports.language(id, description) values ('ven' ,'Venda');
insert into bisis_reports.language(id, description) values ('vie' ,'Vijetnamski');
insert into bisis_reports.language(id, description) values ('vol' ,'Volapuk');
insert into bisis_reports.language(id, description) values ('vot' ,'Votic');
insert into bisis_reports.language(id, description) values ('wak' ,'Vakaški jezici');
insert into bisis_reports.language(id, description) values ('wal' ,'Walamo');
insert into bisis_reports.language(id, description) values ('war' ,'Waray');
insert into bisis_reports.language(id, description) values ('was' ,'Washo');
insert into bisis_reports.language(id, description) values ('wel' ,'Velški');
insert into bisis_reports.language(id, description) values ('wen' ,'Lužičkosrpski');
insert into bisis_reports.language(id, description) values ('wln' ,'Walloon');
insert into bisis_reports.language(id, description) values ('wol' ,'Volof');
insert into bisis_reports.language(id, description) values ('xal' ,'Kalmyk');
insert into bisis_reports.language(id, description) values ('xho' ,'Xhosa');
insert into bisis_reports.language(id, description) values ('yao' ,'Jao');
insert into bisis_reports.language(id, description) values ('yap' ,'Yapese');
insert into bisis_reports.language(id, description) values ('yid' ,'Jidiš');
insert into bisis_reports.language(id, description) values ('yor' ,'Yoruba');
insert into bisis_reports.language(id, description) values ('ypk' ,'Yupik languages');
insert into bisis_reports.language(id, description) values ('zap' ,'Zapotec');
insert into bisis_reports.language(id, description) values ('zbl' ,'Blissymbolics');
insert into bisis_reports.language(id, description) values ('zen' ,'Zenaga');
insert into bisis_reports.language(id, description) values ('zha' ,'Zhuang / Chuang');
insert into bisis_reports.language(id, description) values ('znd' ,'Zande');
insert into bisis_reports.language(id, description) values ('zul' ,'Zulu');
insert into bisis_reports.language(id, description) values ('zun' ,'Zuni');
insert into bisis_reports.language(id, description) values ('zxx' ,'No linguistic content');
insert into bisis_reports.language(id, description) values ('zza' ,'Zaza');
update bisis_reports.language set description = concat(id, ' - ', description);
insert into bisis_reports.language(id, description) values ('nemavrednost' ,'Нема вредност');
