server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  profiles:
    active: development

---

spring:
  profiles: development
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/?replicaSet=bisis5
      database: bisis
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

---

spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://bisis1:27017,bisis2:27017,bisis3:27017/?replicaSet=bisis5
      database: bisis
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

---
