package com.ftninformatika.bisis.rest_service.bisis4_model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Godina generated by hbm2java
 */
public class Godina implements java.io.Serializable {

  private int godinaID;
  private String invBroj;
  private Date datumRacuna;
  private String brojRacuna;
  private String dobavljac;
  private BigDecimal cena;
  private String finansijer;
  private Date datumInventarisanja;
  private String sigFormat;
  private String sigPodlokacija;
  private String sigIntOznaka;
  private String sigDublet;
  private String sigNumerusCurens;
  private String sigNumeracija;
  private String sigUDK;
  private String povez;
  private String nacinNabavke;
  private String odeljenje;
  private String napomene;
  private String godiste;
  private String godina;
  private String broj;
  private String dostupnost;
  private String inventator;
  private List<Sveska> sveske;

}
