package com.ftninformatika.bisis.rest_service.bisis4_model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.util.Date;

/**
 * Lending generated by hbm2java
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Lending implements java.io.Serializable {

	@Id
	private String _id;

	private int location;
	private String librarianLend;
	private String librarianReturn;
	private String librarianResume;
	private String ctlgNo;
	private Date lendDate;
	private Date returnDate;
	private Date resumeDate;
    private Date deadline;
  	//private Set warningses = new HashSet(0);

	/** minimal constructor */
	public Lending(String id, int location,
			String librarianLend, String ctlgNo, Date lendDate) {
		this._id = id;
		this.location = location;
		this.librarianLend = librarianLend;
		this.ctlgNo = ctlgNo;
		this.lendDate = lendDate;
    
	}



}
