package com.ftninformatika.bisis.rest_service.bisis4_model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

/**
 * Records generated by hbm2java
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "#{libraryPrefixProvider.getLibPrefix()}_records")
public class Records implements java.io.Serializable {

  @Id
  private String _id;
  private int recordID;
  private int pubType;
  private List<Field> fields;
  private List<Primerak> primerci;
  private List<Godina> godine;
  private Author creator;
  private Author modifier;
  private String creationDate; //Date
  private String lastModifiedDate; //Date

  /** minimal constructor */
  /*public Records(int recordID, int pubType, Author creator, Date creationDate) {
    this.recordID = recordID;
    this.pubType = pubType;
    this.creator = creator;
    this.creationDate = creationDate;
  }*/

}
