package com.ftninformatika.bisis.rest_service.bisis4_model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Sveska generated by hbm2java
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Sveska implements java.io.Serializable {

  private int sveskaID;
  private String invBroj;
  private String status;
  private String datumStatusa; //Date

  private int stanje;
  private String signatura;
  private BigDecimal cena;
  private String brojSveske;
  private String knjiga;
  private String inventator;
  private int version;


}
