
logging:
  level:
    root: INFO
spring:
  profiles:
    active: development


security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisisdev



logging:
  level:
    com.ftninformatika: INFO

mongeez:
  location: db/mongeez.xml
  database: bisisdev

---
spring:
  profiles: reporting
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisisdev
  main:
    web-environment: false


logging:
  level:
    com.ftninformatika: INFO
---