
logging:
  level:
    root: INFO

spring:
  profiles:
    active: test

security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: developmentCluster
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://bisis:bisis@192.168.200.1:27017,192.168.200.46:27017,192.168.200.3:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 192.168.200.1:9300, 192.168.200.3:9300


logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://localhost:27017
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: localhost:9300


logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: developmentSingle
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis

    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: production
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://bisis1:27017,bisis2:27017,bisis3:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 192.168.45.20:9300, 192.168.45.21:9300


logging:
  level:
    com.ftninformatika: INFO

---
