
logging:
  level:
    root: INFO

spring:
  profiles:
    active: production

security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis
    elasticsearch:
        properties:
          indices:
            query:
              bool:
                max_clause_count: 1000000
#          index:
#            max_result_window: 20000
#          path:
#            data: C:/elasticsearch_storage

  mail:
    host: smtp.gmail.com
    port: 587
    username: ftninformatika@gmail.com
    password: bisis123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    com.ftninformatika: INFO

#mongeez:
#  location: db/mongeez.xml
#  database: bisisdev

---

spring:
  profiles: reporting
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 10_11_bisis
  main:
    web-environment: false

---

spring:
  profiles: production
  data:
    mongodb:
      host: localhost
      port: 27017
 #     username: bisis
      database: bisis
      #uri: mongodb://bisis:bisis@94.130.24.103:27017/bisisdev
#      password: bisis

    elasticsearch:
      properties:
        path:
          data: /opt/elasticsearch_storage

  mail:
    host: smtp.gmail.com
    port: 587
    username: ftninformatika@gmail.com
    password: bisis123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    com.ftninformatika: INFO

---

