
logging:
  level:
    root: INFO

spring:
  profiles:
    active: developmentSingle


security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: developmentCluster
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://bisis:bisis@192.168.200.1:27017,192.168.200.58:27017,192.168.200.3:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 192.168.200.1:9300, 192.168.200.3:9300
serverOrigin: http://localhost:8080/
opacOrigin: http://localhost:4200/
logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: localhost:9300
serverOrigin: https://test.bisis.rs/bisisWS/
opacOrigin: https://bisis5-opac2.firebaseapp.com/
logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: developmentSingle
#  data.mongodb.uri: mongodb://127.0.0.1:27017/?replicaSet=bisis5
#  data.mongodb.database: bisis
  data:
#    redis:
#      repositories:
#        enabled: false
    mongodb:
      host: localhost
      port: 27017
      database: bisis
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
serverOrigin: http://localhost:8080/
opacOrigin: http://localhost:4200/
logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: production
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://bisis1:27017,bisis2:27017,bisis3:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 192.168.45.20:9300, 192.168.45.21:9300
serverOrigin: https://app.bisis.rs/bisisWS/
opacOrigin: https://app.bisis.rs/
logging:
  level:
    com.ftninformatika: INFO

---
