
logging:
  level:
    root: INFO

spring:
  profiles:
    active: development

---

spring:
  profiles: development
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://127.0.0.1:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 127.0.0.1:9300
serverOrigin: https://opactest.bisis.rs/bisisWS/
opacOrigin: https://opactest.bisis.rs/
firebase:
  config: bisis-firebase.json
logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: localhost:9300
serverOrigin: https://admintest.bisis.rs/bisisWS/
opacOrigin: https://opactest.bisis.rs/
logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: developmentSingle
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
serverOrigin: http://localhost:8080/
opacOrigin: http://localhost:4200/
logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: production
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://bisis1:27017,bisis2:27017,bisis3:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 192.168.45.20:9300, 192.168.45.21:9300
serverOrigin: https://opac.bisis.rs/bisisWS/
opacOrigin: https://opac.bisis.rs/
logging:
  level:
    com.ftninformatika: INFO

---
