
logging:
  level:
    root: INFO
spring:
  profiles:
    active: development


security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisisdev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ftninformatika@gmail.com
    password: bisis123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    com.ftninformatika: INFO

mongeez:
  location: db/mongeez.xml
  database: bisisdev

---
spring:
  profiles: reporting
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisisdev
  main:
    web-environment: false
---