
logging:
  level:
    root: INFO

spring:
  profiles:
    active: development

security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ftninformatika@gmail.com
    password: bisis123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: reporting
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis
  main:
    web-environment: false

---

spring:
  profiles: index
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis
    elasticsearch:
          cluster-nodes: localhost:9300
          repositories:
            enabled: true
  main:
    web-environment: false

---

spring:
  profiles: production
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis

    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ftninformatika@gmail.com
    password: bisis123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    com.ftninformatika: INFO

---

