logging:
  level:
    root: INFO

security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisisdev



logging:
  level:
    com.ftninformatika: DEBUG

mongeez:
  location: db/mongeez.xml
  database: bisisdev



---