
logging:
  level:
    root: INFO

spring:
  profiles:
    active: development

security:
  token:
    secret:
      key: megaSecretKey

---

spring:
  profiles: development
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb://192.168.200.46:27017,192.168.200.3:27017/?replicaSet=bisis5
  data:
    elasticsearch:
      cluster-name: bisis5
      cluster-nodes: 192.168.200.1:9300, 192.168.200.3:9300


logging:
  level:
    com.ftninformatika: INFO

---

spring:
  profiles: reporting
  data:
    mongodb:
      host: localhost
      port: 27018
      database: bisis
  main:
    web-environment: false

---

spring:
  profiles: index
  data:
    mongodb:
      host: localhost
      port: 27018
      database: bisis
    elasticsearch:
          cluster-nodes: 192.168.200.171:9300, 192.168.200.5:9300
          repositories:
            enabled: true
          cluster-name: bisis-cluster

  main:
    web-environment: false

---

spring:
  profiles: production
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bisis

    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true

logging:
  level:
    com.ftninformatika: INFO

---

