spring:
  profiles:
    active: development

logging:
  level:
    com.ftninformatika: INFO

---
spring:
  profiles: development
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bisis
    username: postgres
    password: postgres
  data.mongodb.uri: mongodb://127.0.0.1:27017/?replicaSet=bisis5
  data.mongodb.database: bisis
