package com.ftninformatika.bisis.service;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Iterator;
import java.util.List;

/**
 * Records generated by hbm2java
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
//@Document(collection = "#{libraryPrefixProvider.getLibPrefix()}_records")
public class Records implements java.io.Serializable {

  //@Id
  private String _id;
  private int recordID;
  private int pubType;
  private List<Field> fields;
  private List<Primerak> primerci;
  private List<Godina> godine;
  private Author creator;
  private Author modifier;
  //@DateTimeFormat(pattern = "yyyy-MM-dd")
  private String creationDate; //Date
 // @DateTimeFormat(pattern = "yyyy-MM-dd")
  private String lastModifiedDate; //Date


  /**
   * Removes empty fields, subfields, and subsubfields from this record.
   */
  public void pack() {
   /* Iterator it = fields.iterator();
    while (it.hasNext()) {
      com.ftninformatika.bisis.records.Field f = (com.ftninformatika.bisis.service.Field)it.next();
      f.pack();
      if (f.getSubfieldCount() == 0)
        it.remove();
    }*/
  }

  /** minimal constructor */
  /*public Records(int recordID, int pubType, Author creator, Date creationDate) {
    this.recordID = recordID;
    this.pubType = pubType;
    this.creator = creator;
    this.creationDate = creationDate;
  }*/

}
